attributes_on_same_line_as_field = false
attributes_on_same_line_as_variant = false
closure_block_indent_threshold = 1
control_style = "Legacy"
force_format_strings = true
format_strings = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
tab_spaces = 2
where_density = "Vertical"
wrap_comments = true
