array_width = 80
attributes_on_same_line_as_field = false
attributes_on_same_line_as_variant = false
binop_separator = "Back"
chain_one_line_max = 80
closure_block_indent_threshold = 0
control_style = "Legacy"
control_brace_style = "AlwaysSameLine"
fn_brace_style = "PreferSameLine"
fn_call_width = 80
force_format_strings = true
format_strings = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
item_brace_style = "PreferSameLine"
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
single_line_if_else_max_width = 80
struct_lit_width = 80
struct_variant_width = 80
tab_spaces = 2
where_density = "Compressed"
wrap_comments = true
